package com.hospital.backend.dto;

/*
=========================================================
PURPOSE OF THIS CLASS
=========================================================

This is Appointment DTO.

DTO means:

Data Transfer Object

Purpose:

Transfer appointment data

between:

Client

Controller

Service

---------------------------------------------------------

It is NOT database entity.

It is transport object.

Used for:

API requests

API responses

Validation

Safe data transfer

=========================================================
*/

import com.hospital.backend.entity.Appointment.AppointmentStatus;

import jakarta.validation.constraints.*;

import lombok.*;

import java.time.LocalDateTime;

/*
Generates:

getters

setters

toString

equals

hashCode
*/
@Data

/*
 * Builder pattern.
 */
@Builder

/*
 * Empty constructor.
 */
@NoArgsConstructor

/*
 * All arguments constructor.
 */
@AllArgsConstructor
public class AppointmentDTO {

	/*
	 * ================================================== DATABASE ID
	 * 
	 * Primary key.
	 * 
	 * Usually generated by database.
	 * 
	 * Not sent during create.
	 * 
	 * Returned in response. ==================================================
	 */
	private Long id;

	/*
	 * ================================================== PATIENT ID
	 * 
	 * Which patient booked appointment.
	 * 
	 * Foreign key reference:
	 * 
	 * patients.id
	 * 
	 * Validation:
	 * 
	 * Cannot be null. ==================================================
	 */
	@NotNull(message = "Patient ID is required")
	private Long patientId;

	/*
	 * ================================================== DOCTOR ID
	 * 
	 * Which doctor appointment belongs to.
	 * 
	 * Foreign key:
	 * 
	 * doctors.id ==================================================
	 */
	@NotNull(message = "Doctor ID is required")
	private Long doctorId;

	/*
	 * ================================================== APPOINTMENT DATE/TIME
	 * 
	 * When appointment happens. ==================================================
	 */
	@NotNull(message = "Appointment date/time is required")
	private LocalDateTime appointmentDateTime;

	/*
	 * Appointment status.
	 * 
	 * Examples:
	 * 
	 * SCHEDULED
	 * 
	 * CONFIRMED
	 * 
	 * COMPLETED
	 * 
	 * CANCELLED
	 */
	private AppointmentStatus status;

	/*
	 * Why patient booked appointment.
	 * 
	 * Example:
	 * 
	 * Fever
	 * 
	 * Headache
	 * 
	 * Checkup
	 */
	private String reason;

	/*
	 * Doctor notes.
	 * 
	 * Optional.
	 * 
	 * Example:
	 * 
	 * Bring previous reports.
	 */
	private String notes;

	/*
	 * ================================================== READ ONLY RESPONSE FIELDS
	 * ==================================================
	 * 
	 * These are NOT input fields.
	 * 
	 * These are enriched fields.
	 * 
	 * Sent only in responses. ==================================================
	 */

	/*
	 * Instead of only patientId=1
	 * 
	 * Frontend also gets:
	 * 
	 * John Doe
	 */
	private String patientName;

	/*
	 * Doctor full name.
	 */
	private String doctorName;

	/*
	 * Doctor specialization.
	 * 
	 * Cardiology
	 * 
	 * Neurology
	 */
	private String doctorSpecialization;

}