package com.hospital.backend.dto;

/*
=========================================================
PURPOSE OF THIS CLASS
=========================================================

This is Doctor DTO.

DTO means:

Data Transfer Object

Used to move doctor data between:

Frontend

Controller

Service

---------------------------------------------------------

This represents:

Doctor Master Data

in ERP.

Master data means:

Core reference data used by system.

Examples:

Doctors

Patients

Medicines

Departments

=========================================================
*/

import jakarta.validation.constraints.*;

import lombok.*;

/*
Generates:

getters

setters

toString

equals

hashCode
*/
@Data

/*
 * Builder pattern.
 */
@Builder

/*
 * Empty constructor.
 */
@NoArgsConstructor

/*
 * All fields constructor.
 */
@AllArgsConstructor
public class DoctorDTO {

	/*
	 * ================================================== PRIMARY KEY
	 * 
	 * Doctor ID
	 * 
	 * Usually generated by database.
	 * ==================================================
	 */
	private Long id;

	/*
	 * Doctor first name.
	 * 
	 * Required field.
	 */
	@NotBlank(message = "First name is required")
	private String firstName;

	/*
	 * Doctor last name.
	 */
	@NotBlank(message = "Last name is required")
	private String lastName;

	/*
	 * Medical specialization.
	 * 
	 * Examples:
	 * 
	 * Cardiology
	 * 
	 * Neurology
	 * 
	 * Orthopedics
	 */
	@NotBlank(message = "Specialization is required")
	private String specialization;

	/*
	 * Medical license number.
	 * 
	 * Usually unique.
	 * 
	 * Very important field.
	 * 
	 * Used to identify doctor legally.
	 */
	@NotBlank(message = "License number is required")
	private String licenseNumber;

	/*
	 * Email validation.
	 * 
	 * Checks format.
	 */
	@Email(message = "Invalid email")
	private String email;

	/*
	 * Phone number.
	 */
	private String phone;

	/*
	 * Doctor qualifications.
	 * 
	 * Examples:
	 * 
	 * MBBS
	 * 
	 * MD
	 * 
	 * MS
	 */
	private String qualification;

	/*
	 * Doctor biography.
	 * 
	 * Experience.
	 * 
	 * Profile.
	 * 
	 * Can be long text.
	 */
	private String bio;

	/*
	 * Doctor availability.
	 * 
	 * true
	 * 
	 * false
	 * 
	 * Used for appointment booking.
	 */
	private boolean available;

	/*
	 * ================================================== LINK TO USER TABLE
	 * ==================================================
	 * 
	 * This connects doctor
	 * 
	 * to security user account.
	 * 
	 * Very important relationship.
	 * 
	 * doctor.user_id
	 * 
	 * -> users.id ==================================================
	 */
	private Long userId;

}