
##############################################################
# SERVER CONFIGURATION
##############################################################

# Application will run on port 8080

# Browser:
# http://localhost:8080

server.port=8080



##############################################################
# DATABASE CONFIGURATION
##############################################################

# JDBC connection URL

# jdbc:mysql://
# tells Java:
# connect to MySQL database


# localhost
# database is on local machine


# 3306
# default MySQL port


# hospital_db
# database name


# createDatabaseIfNotExist=true

# If hospital_db does not exist
# Spring/Hibernate creates it automatically


# useSSL=false

# disable SSL for local development


# allowPublicKeyRetrieval=true

# needed for some MySQL auth modes


# serverTimezone=UTC

# avoids timezone issues
# for LocalDateTime fields

spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC




# MySQL username

spring.datasource.username=root




# MySQL password

# Used by Spring Boot
# to login to database

spring.datasource.password=Ashish#1818




# MySQL JDBC Driver

# Driver translates Java <-> MySQL communication

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver





##############################################################
# JPA / HIBERNATE CONFIG
##############################################################

# IMPORTANT

# update means:

# compare Entities with database tables

# and update schema automatically


# If Patient entity changed

# add new column

# Hibernate updates table


# Great for development


# In production usually:
# validate

# or Flyway/Liquibase migrations

spring.jpa.hibernate.ddl-auto=update




# Show SQL generated by Hibernate

# Example:

# select * from patients

# insert into doctors ...

spring.jpa.show-sql=true




# Pretty format SQL

# easier to read in logs

spring.jpa.properties.hibernate.format_sql=true






##############################################################
# JWT CONFIGURATION
##############################################################

# Secret used to SIGN JWT tokens

# VERY IMPORTANT

# JwtService reads:

# @Value("${app.jwt.secret}")


# injected from here


# Used here:

# Keys.hmacShaKeyFor(secret.getBytes())

app.jwt.secret=HospitalERPSecretKey2024VeryLongSecretKeyAtLeast256BitsRequired123456




# JWT expiration

# milliseconds

# 86400000 = 24 hours

app.jwt.expiration=86400000






##############################################################
# LOGGING CONFIGURATION
##############################################################

# Show your application's debug logs

logging.level.com.hospital=DEBUG



# Show Spring Security logs

# VERY useful for:

# login failures

# JWT issues

# authorization problems

logging.level.org.springframework.security=DEBUG
